Mozhdeh's homework
wearecodets/hw1-mozhdeh-ahmadi pull request #1
Opened 2019-06-27 05:31 UTC by mozhdeh-ahmadi

🚨 REMEMBER

1️⃣ We will review together the work you have done so far. 

2️⃣ Add my name in the Reviewers section in the right sidebar 👉👉👉

3️⃣ Answer these reflection questions before each PR:

  * What was most challenging about the homework so far? 

  * How did you solve it?

2019-06-27 06:35 UTC, nikosolihin requested changes
@mozhdeh-ahmadi I can't review anything since all your files are empty.

2019-06-27 09:04 UTC, mozhdeh-ahmadi commented
I have finished it! @nikosolihin

2019-06-28 02:55 UTC, nikosolihin requested changes
@mozhdeh-ahmadi Please make these corrections before we merge to master today.

2019-06-28 02:55 UTC, nikosolihin commented on forking.md
> +https://github.com/mozhdeh-ahmadi/best_animals
Your `birds.txt` and `fish.txt` files are still empty. Once you push some changes to the repo, I'll mark this as correct.

2019-06-28 02:55 UTC, nikosolihin commented on googling.md
> +   Phrase 1: what are the Ruby error  messages with meaning?
This is quite generic for a Google phrase. Something like `ruby unterminated string meets end of file` will probably get you closer to the relevant results.

2019-06-28 02:55 UTC, nikosolihin commented on googling.md
> +  Phrase 2: how can i fix a string error message in Ruby program?
Same as my comment above — you need the actual error message.

2019-06-28 02:55 UTC, nikosolihin commented on googling.md
> + Phrase 2: how can i git log in a mod 0?
I'd say the mod0 program is irrelevant in this case. You'd be better off including the keyword `git` like `git log in oneline`.

2019-06-28 02:55 UTC, nikosolihin commented on terminal.md
> +cd  cd  work/projects-delegate
Did you mean `cd ..`

2019-06-28 02:55 UTC, nikosolihin commented on terminal.md
> +cd ..
This should actually be `cd home`

2019-06-28 02:55 UTC, nikosolihin commented on terminal.md
> +cd  .. cd ..  cd rm  cleaning.txt
You miss `cd home` before removing cleaning.txt

2019-07-25 07:28 UTC, merged